server:
  port: 8888
spring:
  config:
    activate:
      on-profile: prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-cn-south-1-8f338385086a4827.rds.jdcloud.com/mps_manage?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: mps_user
    password: sW3aV4sN0uL6bP
    #连接池配置
    hikari: # 时间单位均为ms
      minimum-idle: 5 # 建议不设置，但如使用idle-timeout，该值需要小于maximum-pool-size
      maximum-pool-size: 100 # 最大连接池
      auto-commit: true # 默认
      idle-timeout: 300000 # 该值建议小于max-lifetime
      max-lifetime: 600000 # 该值建议小于数据库的连接关闭等待时间
      connection-timeout: 20000 # 默认30s，连接超时会报异常
      validation-timeout: 5000 # 支持JDBC4的是isValid超时时间 ，不支持的是testQuery超时时间
      connection-test-query: 'SELECT 1' # 支持JDBC4的不建议使用，因为JDBC4的isValid方法效率更高
  jpa:
    hibernate:
      ddlAuto: update
    showSql: false
    properties:
      hibernate:
        session_factory:
          interceptor: com.yn.printer.service.interceptor.AuditInterceptor
  redis:
    database: 1
    host: 172.16.0.6
    port: 6379
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 20000
    password:
api:
  # 微信小程序相关接口url
  wx:
    # 小程序登录
    loginUrl: https://api.weixin.qq.com/sns/jscode2session
    # 获取小程序接口调用凭证
    getAccessTokenUrl: https://api.weixin.qq.com/cgi-bin/token
    # 获取用户手机号
    getPhoneNumberUrl: https://api.weixin.qq.com/wxa/business/getuserphonenumber
    applet:
      # 小程序 appid
      appid: wx5b66e47c8a23f684
      # 小程序 secret
      secret: 0a08108a1e0951bcc6d7d17e8c6f212b
    pay:
      # 商户号
      mchId: 1666324656
      # 支付状态回调地址
      notifyUrl: https://mps.xlmalls.com/api/order/wxPayCallback
      # 商户API私钥路径
      privateKeyPath: /opt/certs/1666324656_20240119_cert/apiclient_key.pem
      #商户证书序列号
      merchantSerialNumber: 1BA87299355A97019FE913725F5E34069F464EC1
      # 商户APIV3密钥
      apiV3key: 1426yoqfqtf4gfm4xb9lcz67l1awtlrh
  # 天章支付相关接口url
  tz:
    # 创建订单
    createOrderUrl: https://cashier.xlmalls.com/b2c/mps/buildorder
    # 创建支付码
    createQrCodeUrl: https://cashier.xlmalls.com/b2c/mps/qrcode
    # 查询支付结果
    queryPayResultUrl: https://cashier.xlmalls.com/b2c/mps/payresult
  # 阿里云接口url
  ali:
    # 证件照制作
    idPhoto:
      makeUrl: https://idp2.market.alicloudapi.com/idphoto/make

## MQTT##
mqtt:
  host: tcp://172.16.0.6:1883
  userName: admin
  passWord: public
  clientId: tzdy-service-mps04
  completionTimeout: 10000
  heartbeat: 10
  topicSendDevice: /tzdy/send/device/
  topicReceiveDevice: /tzdy/receive/device/
  topicSendQos: 2
  topicReceiveQos: 2
## 文件相关
file:
  basePath:
    /yn-shared-printer/files/
  previewPath:
    https://mps.xlmalls.com/files/
  ossPath:
    https://mps-oss-south.s3.cn-south-1.jdcloud-oss.com/
  ossPath1:
    https://mps-oss-south.s3-internal.cn-south-1.jdcloud-oss.com/

oss:
  jd:
    keyId: JDC_711AC05B56BF7F42EB2E4270BD96
    keySecret: D7ABEE1C809EE23B9951A1BCF55A90E3

  s3:
    bucketName : mps-oss-south
    region: cn-south-1
    endpoint: https://s3.cn-south-1.jdcloud-oss.com
    endpoint1: https://s3-internal.cn-south-1.jdcloud-oss.com

common:
  instance: 0
